apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-web-service-composition
  labels:
    provider: aws
    environment: '*'
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: composite.example.com/v1
    kind: XAWSWebService
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: kms-key
        base:
          apiVersion: kms.aws.upbound.io/v1beta1
          kind: Key
          metadata:
            labels:
              purpose: web-service-encryption
          spec:
            forProvider:
              description: KMS key for web service encryption
              enableKeyRotation: true
              keyPolicy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\"\
                : \"EnableRootAccess\",\n      \"Effect\": \"Allow\",\n      \"Principal\": {\"AWS\":\
                \ \"*\"},\n      \"Action\": \"kms:*\",\n      \"Resource\": \"*\"\n    }\n  ]\n}\n"
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.description
          transforms:
          - type: string
            string:
              fmt: "KMS key for web service \u2014 %s environment"
              type: Format
      - name: s3-bucket
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          metadata:
            labels:
              purpose: web-assets
          spec:
            forProvider:
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s'
          toFieldPath: spec.forProvider.bucket
      - name: s3-bucket-versioning
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketVersioning
          metadata: {}
          spec:
            forProvider:
              status: Enabled
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s'
          toFieldPath: spec.forProvider.bucketName
      - name: s3-public-access-block
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketPublicAccessBlock
          metadata: {}
          spec:
            forProvider:
              blockPublicAcls: true
              blockPublicPolicy: true
              ignorePublicAcls: true
              restrictPublicBuckets: true
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s'
          toFieldPath: spec.forProvider.bucket
      - name: s3-bucket-encryption
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketEncryption
          metadata: {}
          spec:
            forProvider:
              serverSideEncryptionConfiguration:
              - sseAlgorithm: AES256
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s'
          toFieldPath: spec.forProvider.bucket
      - name: db-subnet-group
        base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: DBSubnetGroup
          metadata:
            labels:
              purpose: web-service
          spec:
            forProvider:
              description: DB subnet group for web service
              subnetIds: []
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - fromFieldPath: spec.vpc.subnetIds
          toFieldPath: spec.forProvider.subnetIds
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.name
          transforms:
          - type: string
            string:
              fmt: web-service-%s
              type: Format
      - name: rds-instance
        base:
          apiVersion: rds.aws.upbound.io/v1beta1
          kind: Database
          metadata:
            labels:
              purpose: web-service
          spec:
            forProvider:
              allocatedStorage: 20
              engine: postgres
              engineVersion: '16'
              instanceClass: db.t3.micro
              deletionProtection: true
              publiclyAccessible: false
              backupRetentionPeriod: 7
              backupWindow: 04:00-05:00
              maintenanceWindow: Mon:05:00-Mon:06:00
              multiAZ: false
              storageEncrypted: false
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - fromFieldPath: spec.database.instanceClass
          toFieldPath: spec.forProvider.instanceClass
        - fromFieldPath: spec.database.allocatedStorage
          toFieldPath: spec.forProvider.allocatedStorage
        - fromFieldPath: spec.database.multiAZ
          toFieldPath: spec.forProvider.multiAZ
        - fromFieldPath: spec.database.backupRetentionDays
          toFieldPath: spec.forProvider.backupRetentionPeriod
        - fromFieldPath: spec.database.deletionProtection
          toFieldPath: spec.forProvider.deletionProtection
        - fromFieldPath: spec.database.engineVersion
          toFieldPath: spec.forProvider.engineVersion
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.dbInstanceIdentifier
          transforms:
          - type: string
            string:
              fmt: web-service-%s
              type: Format
        - type: FromCompositeFieldPath
          fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.dbSubnetGroupName
          transforms:
          - type: string
            string:
              fmt: web-service-%s
              type: Format
        - fromFieldPath: spec.environment
          toFieldPath: spec.forProvider.storageEncrypted
          transforms:
          - type: map
            map:
              prod: 'true'
              dev: 'false'
      - name: iam-role
        base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Role
          metadata:
            labels:
              purpose: web-service
          spec:
            forProvider:
              assumeRolePolicy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"\
                Effect\": \"Allow\",\n      \"Principal\": {\"AWS\": \"*\"},\n      \"Action\": \"sts:AssumeRole\"\
                \n    }\n  ]\n}\n"
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - fromFieldPath: spec.iam.roleName
          toFieldPath: spec.forProvider.roleName
        - fromFieldPath: spec.iam.oidcProviderArn
          toFieldPath: spec.forProvider.assumeRolePolicy
          transforms:
          - type: string
            string:
              fmt: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"\
                Allow\",\n      \"Principal\": {\"Federated\": \"%s\"},\n      \"Action\": \"sts:AssumeRoleWithWebIdentity\"\
                ,\n      \"Condition\": {\"StringEquals\": {\"%s:sub\": \"system:serviceaccount:*:*\"\
                }}\n    }\n  ]\n}\n"
              type: Format
      - name: iam-policy
        base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: Policy
          metadata:
            labels:
              purpose: web-service
          spec:
            forProvider:
              tags:
                managed-by: crossplane
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - fromFieldPath: spec.iam.roleName
          toFieldPath: spec.forProvider.policyName
          transforms:
          - type: string
            string:
              fmt: '%s-permissions'
              type: Format
        - type: FromCompositeFieldPath
          fromFieldPath: spec.iam.roleName
          toFieldPath: spec.forProvider.policy
          transforms:
          - type: string
            string:
              fmt: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"S3Access\"\
                ,\n      \"Effect\": \"Allow\",\n      \"Action\": [\"s3:GetObject\", \"s3:PutObject\"\
                , \"s3:ListBucket\"],\n      \"Resource\": [\"arn:aws:s3:::web-assets-%s\", \"arn:aws:s3:::web-assets-%s/*\"\
                ]\n    },\n    {\n      \"Sid\": \"RDSAccess\",\n      \"Effect\": \"Allow\",\n      \"\
                Action\": [\"rds:DescribeDBInstances\"],\n      \"Resource\": \"arn:aws:rds:*:*:db:web-service-%s\"\
                \n    },\n    {\n      \"Sid\": \"KMSAccess\",\n      \"Effect\": \"Allow\",\n      \"\
                Action\": [\"kms:Decrypt\", \"kms:GenerateDataKey\", \"kms:DescribeKey\"],\n      \"Resource\"\
                : \"*\"\n    }\n  ]\n}\n"
              type: Format
      - name: iam-role-policy-attachment
        base:
          apiVersion: iam.aws.upbound.io/v1beta1
          kind: RolePolicyAttachment
          metadata: {}
          spec:
            forProvider: {}
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - fromFieldPath: spec.iam.roleName
          toFieldPath: spec.forProvider.roleName
        - fromFieldPath: spec.iam.roleName
          toFieldPath: spec.forProvider.policyArn
          transforms:
          - type: string
            string:
              fmt: '%s-permissions'
              type: Format
      - name: s3-replication-destination
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: Bucket
          metadata:
            labels:
              purpose: replication-destination
          spec:
            forProvider:
              tags:
                managed-by: crossplane
                replication-destination: 'true'
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.secondaryProviderConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s-replica'
          toFieldPath: spec.forProvider.bucket
        - fromFieldPath: spec.environment
          toFieldPath: metadata.labels.environment
      - name: s3-replication-destination-versioning
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketVersioning
          metadata: {}
          spec:
            forProvider:
              status: Enabled
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.secondaryProviderConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s-replica'
          toFieldPath: spec.forProvider.bucketName
      - name: s3-replication-config
        base:
          apiVersion: s3.aws.upbound.io/v1beta1
          kind: BucketReplicationConfiguration
          metadata: {}
          spec:
            forProvider:
              replicationRules:
              - status: Enabled
                destination:
                  storageClass: STANDARD
            managementPolicy: Observe
        patches:
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigName
          toFieldPath: spec.providerConfigReference.name
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s'
          toFieldPath: spec.forProvider.bucket
        - type: CombineFromComposite
          combine:
            variables:
            - fromFieldPath: spec.bucket.name
            - fromFieldPath: spec.environment
            strategy: string
            string:
              fmt: '%s-%s-replica'
          toFieldPath: spec.forProvider.replicationRules[0].destination.bucket
